language: ruby

sudo: false
cache: bundler

rvm:
  - jruby-9.0.0.0
  - 2.0.0
  - 2.3.1

before_install: gem install bundler -v 1.13.1

script: 'bundle exec rake spec'

notifications:
  email:
    recipients:
      - aemadrid@gmail.com
    on_failure: change
    on_success: never